# SEO settings
title: "Lucas"
title2: "Mahieu" # default: ""
description: "This is my professional web page were I store all my interesting research or projects."
keywords: "Jekyll, Computer Science, ENSIMAG, Embedded System, Embedded Software, note, tutorial, project, deep learning"
#url: http://lucasmahieu.github.io # site url
url: http://lucasmahieu.fr # site url
#baseurl: "/thinkspace" # apply repo name if use it under gh-pages branch
baseurl: null # apply null if repo name is something like username.github.io

google_analytics: UA-XXXXX-XX
repo: http://lucasmahieu.git
disqus_shortname: "LucasMahieu"
twitter_username: null
comments: true

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Lucas MAHIEU"
  job      : "French Embedded Software Student Engineer"
  bio      : "I will use this web space to share my works, my researches and other things I find interesting to keep notes"
  thumb    : /images/author.jpg
  email    : contact@lucasmahieu.fr
  url      : http://lucasmahieu.fr
  github   : http://github.com/LucasMahieu
  #twitter  : http://twitter.com/
  #facebook : https://www.facebook.com/profile.php?id=1257583160
  linkedin : http://linkedin.com/in/LucasMahieu

# social settings
og_locale: "en_US"
#twitter_card: "summary_large_image"
#twitter_site: "@HeiswayiNrird"
twitter_card: null
twitter_site: null

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : resume
    title: Resume
  - slug : contact
    title: Contact
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
